// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPhq3RUec-l1xkQWY9N8TBC0uOKvwnJSQ',
    appId: '1:389857741035:web:4d08955f89abb329e096ae',
    messagingSenderId: '389857741035',
    projectId: 'gasense-ee5d9',
    authDomain: 'gasense-ee5d9.firebaseapp.com',
    storageBucket: 'gasense-ee5d9.firebasestorage.app',
    measurementId: 'G-CP1JPHTD27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQvDupN7p5qPCdsLYwYrsnFcWDFOwjTOc',
    appId: '1:389857741035:android:3754736a943be848e096ae',
    messagingSenderId: '389857741035',
    projectId: 'gasense-ee5d9',
    storageBucket: 'gasense-ee5d9.firebasestorage.app',
  );

}